uploads = []
generated = []

[[outputs]]
id = "j7qm67gdRChO6X-hEwG1M"
uri = "file://Queen_Abims_Bot.zip"
type = "unspecified"
title = "Queen Abims Bot — Fixed & Updated (ZIP)"

[[outputs]]
id = "pJPKerl__vt8x8S9q723M"
uri = "file://Queen_Abims_Bot_v2.zip"
type = "unspecified"
title = "Queen Abims Bot v2 — All Features + APIs Fixed"

[[outputs]]
id = "Qc4d0yyn7589EpRa_64vh"
uri = "file://telexwa-main.zip"
type = "unspecified"
title = "Queen Abims Bot — Complete Updated Source"
